{
 "title": "NMX",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.nmx.*" }
  ]
 },
 "panels": [
  {
   "title": "Receive Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.nmx.$region.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.nmx.$region.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.receive.fifo_seq_errors), 'seq err/s')"
    }
   ]
  },
  {
   "title": "ESS Readout Header Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_header), 'header errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_buffer), 'buffer errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_buffer), 'buffer errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_version), 'version errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_output_queue), 'OQ errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_type), 'type errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_seqno), 'seqno errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_timefrac), 'timefrac errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.heartbeats), 'heartbeats/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.essheader.error_pad), 'padding err/s')"
    }
   ]
  },
  {
   "title": "Readout Data Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.headers), 'headers/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.count), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.error_amplitude), 'ampl errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.error_header), 'header errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.error_bytes), 'error bytes/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.error_ring), 'ring errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.readouts.error_fen), 'fen errors/s')"
    }
   ]
  },
  {
   "title": "Geometry Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.nmx.$region.cluster.span.x_too_large), 'X Span Too Large/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.cluster.span.x_too_small), 'X Span Too Small/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.cluster.matched_x_only), 'Matched X Only/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.cluster.matched_y_only), 'Matched Y Only/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.geometry.pos_high), 'clamp LO/s')"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.nmx.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.events.pixel_errors), 'pixel errors/s')"
    },
    {
     "target": "alias(perSecond(efu.nmx.$region.events.udder), 'udder events/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.nmx.$region.thread.processing_idle), 'processing idle/s')"
    },
    {
     "target": "alias(efu.nmx.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Output rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.nmx.$region.transmit.bytes, 8)), 'bis/s')"
    }
   ]
  }
 ]
}