#!/bin/bash

if [[ ! -d $basedir ]] ; then
    echo "No efu directory [$basedir], set EFUBASE environment varuable"
    echo "export EFUBASE=/path/to/efu/repo"
    exit 1
fi

if [[ ! -f $efu ]] ; then
    echo "No EFU binary [$efu], build it first"
    exit 1
fi

if [[ ! -f $config ]] ; then
    echo "No detector config file [$config], check launch script"
    exit 1
fi

if [[ ! $kafkacfg == "" ]] ; then
    kafkacmd="--kafka_config "$kafkacfg
fi

echo Debug: $*
echo $efu  -f $config  -r $region -b $kafka -g $grafana -m $cmdport -p $dataport $kafkacmd $@
$efu  -f $config  -r $region -b $kafka -g $grafana -m $cmdport -p $dataport $kafkacmd $@
