{
 "title": "MultiBlade",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "packets/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.receive.packets)"
    }
   ]
  },
  {
   "title": "bits/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mbcaen.0.receive.packets, 8))"
    }
   ]
  },
  {
   "title": "dropped/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.receive.dropped)"
    }
   ]
  },
  {
   "title": "readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.readouts.count)"
    }
   ]
  },
  {
   "title": "Input rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.0.receive.packets), 'pkts/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mbcaen.0.receive.bytes, 8)), 'bits/s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.0.readouts.count), 'count')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.readouts.count_valid), 'count_valid')"
    }
   ]
  }
 ]
}