{
 "title": "MultiBlade",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "packets/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.receive.packets)"
    }
   ]
  },
  {
   "title": "bits/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mbcaen.0.receive.packets, 8))"
    }
   ]
  },
  {
   "title": "dropped/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.receive.dropped)"
    }
   ]
  },
  {
   "title": "readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.readouts.count)"
    }
   ]
  },
  {
   "title": "events/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.0.events.count)"
    }
   ]
  },
  {
   "title": "Input rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.0.receive.packets), 'pkts/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mbcaen.0.receive.bytes, 8)), 'bits/s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.0.readouts.count), 'count')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.readouts.count_valid), 'count_valid')"
    }
   ]
  },
  {
   "title": "rx errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.0.receive.dropped), 'dropped')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.readouts.seq_errors), 'seq error')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.0.events.count), 'count')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.events.geometry_errors), 'geom. errors')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.events.no_coincidence), 'no coincidence')"
    }
   ]
  },
  {
   "title": "Uptime/idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(efu.mbcaen.0.main.uptime, 'uptime')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.thread.processing_idle), 'idle/s')"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.mbcaen.0.transmit.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.0.kafka.produce_fails), 'prod. fails/s')"
    }
   ]
  }
 ]
}