#!/bin/bash

echo "Starting Zookeeper and Kafka"

cd  ~/essdaq/kafka_2.11-1.1.0/bin

echo "Starting Zookeeper"
./zookeeper-server-start.sh -daemon ~/essdaq/kafka_2.11-1.1.0/config/zookeeper.properties

echo "Starting Kafka"
./kafka-server-start.sh -daemon ~/essdaq/server.config

