{
 "title": "Freia",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.loki.*" }
  ]
 },
 "panels": [
  {
   "title": "Receive Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.freia.$region.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.receive.fifo_seq_errors), 'seq err/s')"
    }
   ]
  },
  {
   "title": "ESS Readout Header Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_header), 'header errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_buffer), 'buffer errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_version), 'version errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_output_queue), 'OQ errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_type), 'type errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_seqno), 'seqno errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_timefrac), 'timefrac errors/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.heartbeats), 'heartbeats/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_pad), 'padding err/s')"
    }
   ]
  },
  {
   "title": "VMM3a Readout Data Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.count), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_ring), 'ring_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_fen), 'fen_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_datalen), 'dlen_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_timefrac), 'timefrac_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_bc), 'bc_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_adc), 'adc_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_vmm), 'vmm_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_channel), 'size_err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.error_size), 'err size/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.data), 'data/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.readouts.bccalib), 'bc_calib/s')"
    }
   ]
  },
  {
   "title": "Clustering",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.events.no_coincidence), 'no coincidence/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.events.strip_gaps), 'strip gap err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.events.wire_gaps), 'wire gap err/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.events.matched_clusters), 'matched clust/s')"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.freia.$region.events.pixel_errors), 'pixel errors/s')"
    }
   ]
  },
  {
   "title": "Time Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.essheader.error_timehigh), 'err_time_hi/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.freia.$region.thread.processing_idle), 'processing idle/s')"
    },
    {
     "target": "alias(efu.freia.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Output rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.freia.$region.transmit.bytes, 8)), 'bis/s')"
    }
   ]
  }
 ]
}