{
 "title": "GdGEM SRS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.gdgem.*" }
  ]
 },
 "panels": [
  {
   "title": "packets/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.rx_packets)"
    }
   ]
  },
  {
   "title": "bits/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.gdgem.$region.rx_bytes, 0.000008))"
    }
   ]
  },
  {
   "title": "dropped/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.i2pfifo_dropped)"
    }
   ]
  },
  {
   "title": "dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.gdgem.$region.i2pfifo_dropped"
    }
   ]
  },
  {
   "title": "readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.readouts_total)"
    }
   ]
  },
  {
   "title": "readouts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(efu.gdgem.$region.readouts_total, 0.000001)"
    }
   ]
  },
  {
   "title": "Input Rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.gdgem.$region.rx_bytes, 8)), 'rx bytes')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.rx_packets), 'rx packets')"
    }
   ]
  },
  {
   "title": "FIFO errors and dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.fifo_seq_errors), 'seq errors')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.i2pfifo_dropped), 'dropped')"
    }
   ]
  },
  {
   "title": "Dropped %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(perSecond(efu.gdgem.$region.i2pfifo_dropped), #C), 100), 'dropped_pct')",
     "targetFull": "alias(scale(divideSeries(perSecond(efu.gdgem.$region.i2pfifo_dropped), perSecond(efu.gdgem.$region.rx_packets)), 100), 'dropped_pct')"
    }
   ]
  },
  {
   "title": "Frames",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.bad_frames), 'bad frames')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.good_frames), 'good frames')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts_error_bytes), 'error bytes')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts_total), 'readouts total')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts_bad_adc), 'readout bad adc')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts_bad_geometry), 'readout bad geometry')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts_good), 'readouts good')"
    }
   ]
  },
  {
   "title": "Cluster events/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.events_good)"
    }
   ]
  },
  {
   "title": "events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "efu.gdgem.$region.events_good" }
   ]
  },
  {
   "title": "error bytes/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.readouts_error_bytes)"
    }
   ]
  },
  {
   "title": "error bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.gdgem.$region.readouts_error_bytes"
    }
   ]
  },
  {
   "title": "txbytes/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.tx_bytes)"
    }
   ]
  },
  {
   "title": "txbytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "efu.gdgem.$region.tx_bytes" }
   ]
  },
  {
   "title": "Clusters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters_total), 'total')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters_x_only), 'x only')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters_y_only), 'y only')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters_xy), 'xy')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.events_good), 'events good')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events_bad_utpc), 'Bad uTPC')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events_geom_errors), 'geometry errors')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events_filter_rejects), 'filter rejects')"
    }
   ]
  },
  {
   "title": "Idle/uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.processing_idle), 'idle count')"
    },
    {
     "target": "alias(efu.gdgem.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.tx_bytes), 'tx bytes')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events_good), 'events good')"
    }
   ]
  },
  {
   "title": "Total x clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(sumSeries(efu.gdgem.$region.clusters_x_only, #B))",
     "targetFull": "perSecond(sumSeries(efu.gdgem.$region.clusters_x_only, efu.gdgem.$region.clusters_xy))"
    }
   ]
  },
  {
   "title": "Total y clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(sumSeries(efu.gdgem.$region.clusters_y_only, #B))",
     "targetFull": "perSecond(sumSeries(efu.gdgem.$region.clusters_y_only, efu.gdgem.$region.clusters_xy))"
    }
   ]
  },
  {
   "title": "Matched x/y clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.clusters_xy)"
    }
   ]
  },
  {
   "title": "Unmatched x clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.clusters_x_only)"
    }
   ]
  },
  {
   "title": "Unmatched y clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.clusters_y_only)"
    }
   ]
  }
 ]
}