{
 "title": "GdGEM SRS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.gdgem.*" }
  ]
 },
 "panels": [
  {
   "title": "packets/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.receive.packets)"
    }
   ]
  },
  {
   "title": "bits/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.gdgem.$region.receive.bytes, 8))"
    }
   ]
  },
  {
   "title": "dropped/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.receive.dropped)"
    }
   ]
  },
  {
   "title": "dropped",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.gdgem.$region.receive.dropped"
    }
   ]
  },
  {
   "title": "readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.readouts.count)"
    }
   ]
  },
  {
   "title": "readouts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.gdgem.$region.readouts.count"
    }
   ]
  },
  {
   "title": "Input Rates",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.gdgem.$region.receive.bytes, 8)), 'rx bytes')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.receive.packets), 'rx packets')"
    }
   ]
  },
  {
   "title": "FIFO errors and dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.receive.fifo_seq_errors), 'seq errors')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.receive.dropped), 'dropped')"
    }
   ]
  },
  {
   "title": "Dropped %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(perSecond(efu.gdgem.$region.receive.dropped), #C), 100), 'dropped_pct')",
     "targetFull": "alias(scale(divideSeries(perSecond(efu.gdgem.$region.receive.dropped), perSecond(efu.gdgem.$region.receive.packets)), 100), 'dropped_pct')"
    }
   ]
  },
  {
   "title": "Frames, Data, Markers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts.good_frames), 'good frames')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts.count), 'readouts')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts.data), 'data')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.readouts.markers), 'markers')"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.hits.good), 'good')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.hits.over_threshold), 'OT')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.hits.bad_adc), 'bad adc')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.hits.bad_geometry), 'bad geometry')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.hits.bad_plane), 'bad plane')"
    }
   ]
  },
  {
   "title": "events/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.events.good)"
    }
   ]
  },
  {
   "title": "events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "efu.gdgem.$region.events.good" }
   ]
  },
  {
   "title": "error bytes/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.readouts.error_bytes)"
    }
   ]
  },
  {
   "title": "error bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.gdgem.$region.readouts.error_bytes"
    }
   ]
  },
  {
   "title": "txbytes/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.transmit.bytes)"
    }
   ]
  },
  {
   "title": "txbytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.gdgem.$region.transmit.bytes"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters.total), 'total')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters.x), 'x only')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters.y), 'y only')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.clusters.x_and_y), 'xy')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.events.good), 'events good')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events.bad), 'bad')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events.geom_errors), 'geometry errors')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events.filter_rejects), 'filter rejects')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events.good_hits), 'good hits')"
    }
   ]
  },
  {
   "title": "Idle/uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.thread.processing_idle), 'idle count')"
    },
    {
     "target": "alias(efu.gdgem.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Output",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.gdgem.$region.transmit.bytes), 'tx bytes')"
    },
    {
     "target": "alias(perSecond(efu.gdgem.$region.events.good), 'events good')"
    }
   ]
  },
  {
   "title": "Total x clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(sumSeries(efu.gdgem.$region.clusters.x_and_y, #B))",
     "targetFull": "perSecond(sumSeries(efu.gdgem.$region.clusters.x_and_y, efu.gdgem.$region.clusters.x))"
    }
   ]
  },
  {
   "title": "Total y clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(sumSeries(efu.gdgem.$region.clusters.x_and_y, #B))",
     "targetFull": "perSecond(sumSeries(efu.gdgem.$region.clusters.x_and_y, efu.gdgem.$region.clusters.y))"
    }
   ]
  },
  {
   "title": "Matched x/y clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.clusters.x_and_y)"
    }
   ]
  },
  {
   "title": "Unmatched x clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.clusters.x)"
    }
   ]
  },
  {
   "title": "Unmatched y clusters/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.gdgem.$region.clusters.y)"
    }
   ]
  },
  {
   "title": "Hits/cluster",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(perSecond(efu.gdgem.$region.hits.good), #B)",
     "targetFull": "divideSeries(perSecond(efu.gdgem.$region.hits.good), perSecond(efu.gdgem.$region.clusters.total))"
    }
   ]
  }
 ]
}