{
 "title": "AMORB",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.mbcaen.*" }
  ]
 },
 "panels": [
  {
   "title": "packets/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.$region.receive.packets)"
    }
   ]
  },
  {
   "title": "bits/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mbcaen.$region.receive.packets, 8))"
    }
   ]
  },
  {
   "title": "dropped/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.$region.receive.dropped)"
    }
   ]
  },
  {
   "title": "readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.$region.readouts.count)"
    }
   ]
  },
  {
   "title": "events/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mbcaen.$region.events.count)"
    }
   ]
  },
  {
   "title": "Input rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.$region.receive.packets), 'pkts/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mbcaen.$region.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mbcaen.$region.receive.dropped, 8)), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mbcaen.$region.receive.fifo_seq_errors, 8)), 'fifo error/s')"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.seq_errors), 'seq error')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.error_version), 'version err')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.count), 'count')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.count_valid), 'count_valid')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.monitor), 'monitors')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.count1D), '1D')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.count2D), '2D')"
    }
   ]
  },
  {
   "title": "Readout Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.invalid_adc), 'bad adc')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.invalid_ch), 'bad channel')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.readouts.invalid_plane), 'bad plane')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.count), 'count')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.geometry_errors), 'geom. errors')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.no_coincidence), 'no coincidence')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.1D), '1D')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.2D), '2D')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.max_tof_ns), 'max TOF')"
    }
   ]
  },
  {
   "title": "Transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.mbcaen.$region.transmit.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.kafka.produce_fails), 'prod. fails/s')"
    }
   ]
  },
  {
   "title": "Uptime/idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "alias(efu.mbcaen.$region.main.uptime, 'uptime')"
    },
    {
     "target": "alias(perSecond(efu.mbcaen.$region.thread.processing_idle), 'idle/s')"
    }
   ]
  }
 ]
}