{
 "title": "TBL3HE",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Receive Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl3he.$region.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.receive.fifo_seq_errors), 'seq err/s')"
    }
   ]
  },
  {
   "title": "ESS Readout Header Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_header), 'header errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_buffer), 'buffer errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_version), 'version errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_output_queue), 'OQ errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_type), 'type errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_seqno), 'seqno errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_timefrac), 'timefrac errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_timehigh), 'max pulse time diff/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.heartbeats), 'heartbeats/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.error_pad), 'padding err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.version.v0), 'v0 header/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.essheader.version.v1), 'v1 header/s')"
    }
   ]
  },
  {
   "title": "Readout Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.count), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.error_ringfen), 'ringfen_err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.error_datlen_invalid), 'dlen_invalid/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.error_datlen_mismatch), 'dlen_mism/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.error_headersize), 'headersz_err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.error_amplitude), 'ampl err/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl3he.$region.thread.processing_idle), 'processing idle/s')"
    },
    {
     "target": "alias(efu.tbl3he.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Time Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.tof_high), 'tof high/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.tof_count), 'tof count/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.tof_neg), 'tof negative/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.prevtof_count), 'prev tof count/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.prevtof_neg), 'prev tof neg/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.readouts.prevtof_high), 'prevtof high/s')"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl3he.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.events.pixel_errors), 'pixel errors/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.ampl_zero), 'ampl zero/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.ring_mapping_errors), 'ring mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.calib_group_errors), 'cal grp err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.fen_mapping_errors), 'fen mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.group_errors), 'group err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.outside_tube), 'outside tube/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.pos_high), 'pos hi/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl3he.$region.geometry.pos_low), 'pos low/s')"
    }
   ]
  },
  {
   "title": "Kafka stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.ev_errors, 8)), 'ev errors/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.ev_others, 8)), 'ev others/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.dr_errors, 8)), 'dr errors/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.dr_others, 8)), 'dr others/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.config_errors, 8)), 'cfg err/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.err_other, 8)), 'err other/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.err_queue_full, 8)), 'err q full/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.err_unknown_topic, 8)), 'err unkn topic/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.produce_calls, 8)), 'produce calls/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.produce_calls, 8)), 'produce calls/s')"
    }
   ]
  },
  {
   "title": "Output rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.produce_bytes_ok, 8)), 'bits ok/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.tbl3he.$region.kafka.produce_bytes_error, 8)), 'bits error/s')"
    }
   ]
  }
 ]
}