{
 "title": "Odin",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Receive",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.bytes), 'Bytes Receive /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.dropped), 'Dropped /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.fifo_seq_errors), 'Seq Errors /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.packets), 'Packets /s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "perSecond(efu.timepix3.1.readouts.globaltimestamp_readout_count)"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.pixel_readout_count), 'Pixel Readouts /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc_readout_count), 'TDC Readouts /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc1falling_readout_count), 'TDC 1 Falling Readouts /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc1rising_readout_count), 'TDC 1 Rising Readouts /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc2falling_readout_count), 'TDC 2 Falling Readouts /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc2rising_readout_count), 'TDC 2 Rising Readouts /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.undefined_readout_count), 'Undefined Readouts /s')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.events.count), 'Events /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.events.pixel_errors), 'Pixel Errors /s')"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(efu.timepix3.1.main.uptime, 'Uptime')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.thread.processing_idle), 'Idle')"
    }
   ]
  }
 ]
}