{
 "title": "Odin",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Receive stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.timepix3.1.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.fifo_seq_errors), 'fifo errors/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.packets), 'packets /s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.globaltimestamp_readout_count), 'Global Timestamp /s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.pixel_readout_count), 'pixels/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc_readout_count), 'TDC/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc1falling_readout_count), 'TDC 1 Falling/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc1rising_readout_count), 'TDC 1 Rising/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc2falling_readout_count), 'TDC 2 Falling/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc2rising_readout_count), 'TDC 2 Rising/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.undefined_readout_count), 'undefined/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.evrtimestamp_readout_count), 'EVR Timestamp/s')"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.events.pixel_errors), 'pixel errors/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(efu.timepix3.1.main.uptime, 'uptime')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.thread.processing_idle), 'idle/s')"
    }
   ]
  }
 ]
}