{
 "title": "Odin",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "ROW TITLE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Receive stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.timepix3.1.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.fifo_seq_errors), 'fifo errors/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.receive.packets), 'packets /s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.pixel_readout_count), 'pixel readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.evr.evr_readout_count), 'evr readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.readouts.tdc.tdc_readout_count), 'tdc readouts/s')"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.handlers.timeingevent.ess_global_time_count), 'global time count/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.handlers.timeingevent.miss_evr_count), 'miss evr errors/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.handlers.timeingevent.miss_tdc_count), 'miss tdc errors/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.handlers.pixelevent.no_global_time_error), 'no global time errors/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(efu.timepix3.1.main.uptime, 'uptime')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.thread.processing_idle), 'idle/s')"
    }
   ]
  },
  {
   "title": "Transmission",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "targets": [
    {
     "target": "alias(perSecond(efu.timepix3.1.kafka.produce_bytes_ok), 'bytes ok/s')"
    },
    {
     "target": "alias(perSecond(efu.timepix3.1.kafka.produce_bytes_error), 'bytes error/s')"
    }
   ]
  }
 ]
}