{
 "title": "magic",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.freia.*" }
  ]
 },
 "panels": [
  {
   "title": "Receive Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.magic.$region.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.magic.$region.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.receive.fifo_seq_errors), 'seq err/s')"
    }
   ]
  },
  {
   "title": "ESS Readout Header Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_header), 'header errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_buffer), 'buffer errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_version), 'version errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_output_queue), 'OQ errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_type), 'type errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_seqno), 'seqno errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_timefrac), 'timefrac errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_timehigh), 'max pulse time diff/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.heartbeats), 'heartbeats/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.error_pad), 'padding err/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.version.v0), 'v0 header/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.essheader.version.v1), 'v1 header/s')"
    }
   ]
  },
  {
   "title": "Readout Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.magic.$region.readouts.count), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts.error_ring), 'ring_err/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts.error_fen), 'fen_err/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts.error_header), 'hdr err/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.magic.$region.thread.processing_idle), 'processing idle/s')"
    },
    {
     "target": "alias(efu.magic.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Time Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.magic.$region.readouts), 'tof too large/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts), 'tof count/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts), 'tof negative/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts), 'prev tof count/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.readouts), 'prev tof neg/s')"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.magic.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.events.geometry_errors), 'pixel errors/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.events), 'strip gap/s')"
    },
    {
     "target": "alias(perSecond(efu.magic.$region.events), 'wire gap/s')"
    }
   ]
  },
  {
   "title": "Kafka stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.magic.$region.kafka.ev_errors, 8)), 'ev errors/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.magic.$region.kafka.ev_others, 8)), 'ev others/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.magic.$region.kafka.dr_errors, 8)), 'dr errors/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.dream.$region.kafka.dr_others, 8)), 'dr others/s')"
    }
   ]
  },
  {
   "title": "Output rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.magic.$region.kafka.produce_bytes_ok, 8)), 'bits ok/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.magic.$region.kafka.produce_bytes_error, 8)), 'bits error/s')"
    }
   ]
  }
 ]
}