#!/bin/bash

osimg=${1:-ubuntu}
container=essdaq$osimg

docker build -f Dockerfile_$osimg -t $container . || exit

containers=$(docker ps -a -q --filter name=$osimg)
if [[ $containers != "" ]]; then
  docker rm $containers
fi

FILESYS="-v /tmp/dockerresults:/tmp/results"
PORTS="-p 8888:8888/tcp -p 9000:9000/udp -p 9092:9092/tcp"
PROXY="--build-arg http_proxy=${http_proxy}"
#PORTS='-P'

docker network prune -f
docker network create --subnet=10.1.0.0/16 essdaqnet

docker run $FILESYS $PORTS $PROXY -it --net essdaqnet --ip 10.1.15.16 --name from_build$osimg $container
