#!/bin/bash

osimg=${1:-ubuntu}
container=essdaq$osimg

if [[ $http_proxy != "" ]]; then
  PROXY="--build-arg http_proxy=$http_proxy"
  DOCENV="-e http_proxy=$http_proxy"
fi

if [[ $https_proxy != "" ]]; then
  PROXY="$PROXY --build-arg https_proxy=$https_proxy"
  DOCENV="$DOCENV -e https_proxy=$https_proxy"
fi

echo "Build Docker image"
docker build $PROXY -f Dockerfile_$osimg -t $container . || exit

containers=$(docker ps -a -q --filter name=$osimg)
if [[ $containers != "" ]]; then
  docker rm $containers
fi

FILESYS="-v /tmp/dockerresults:/tmp/results"
PORTS="-p 8888:8888/tcp -p 9000:9000/udp -p 9092:9092/tcp"

#docker network prune -f
#docker network create --subnet=10.1.0.0/16 essdaqnet
#docker run $FILESYS $PORTS $PROXY -it --net essdaqnet --ip 10.1.15.16 --name from_build$osimg $container
echo "Run Docker image"
docker run $DOCENV $FILESYS $PORTS -i --name from_build$osimg $container
