FROM centos

ENV container docker

USER root

# install CentOS related utilities
RUN yum install -y centos-release-scl epel-release
RUN yum install -y devtoolset-6

# install our own prerequisites
RUN yum install -y vim git cmake3 sudo python36 python36-devel python36-pip
RUN yum autoremove -y
RUN yum clean all

RUN rm -f /usr/bin/cmake
RUN ln -s /usr/bin/cmake3 /usr/bin/cmake

# add sudo user
RUN echo "essdaq ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# create user
RUN useradd -p $1$GDleMP1C$Gk4BMmk/tu9AxXgi/dBcX. -ms /bin/bash essdaq
COPY clone.sh /home/essdaq
RUN chmod 755 /home/essdaq/clone.sh
RUN chown essdaq:essdaq /home/essdaq/clone.sh

# avoid having to type (yes)
COPY known_hosts /home/essdaq/.ssh/
RUN chmod 644 /home/essdaq/.ssh/known_hosts
RUN chown -R essdaq:essdaq /home/essdaq/.ssh

USER essdaq
WORKDIR /home/essdaq
RUN echo "To build essdaq run ./clone.sh"
#CMD ["./clone.sh"]
