FROM centos

ENV container docker

# these commands are run as root
# install CentOS related utilities 
RUN yum install -y centos-release-scl epel-release
RUN yum install -y devtoolset-6

# install our own prerequisites
RUN yum install -y git cmake cmake3 sudo python36 python36-devel python36-pip
RUN yum autoremove -y
RUN yum clean all

# add sudo user
RUN echo "essdaq ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# create user
RUN useradd -p $1$GDleMP1C$Gk4BMmk/tu9AxXgi/dBcX. -ms /bin/bash essdaq
COPY clone.sh /home/essdaq
RUN chmod 755 /home/essdaq/clone.sh

# avoid having to type (yes)
COPY known_hosts /home/essdaq/.ssh/
RUN chmod 644 /home/essdaq/.ssh/known_hosts

USER essdaq
WORKDIR /home/essdaq
RUN echo "To build essdaq run ./clone.sh"
#CMD ["./clone.sh"]
