FROM ubuntu:18.04

ENV container docker

USER root

ARG http_proxy
ARG https_proxy
ARG DEBIAN_FRONTEND=noninteractive
RUN env

# install our own prerequisites
RUN apt-get update
RUN apt-get install -y vim sudo net-tools
RUN apt-get install -y git cmake python3

# add sudo user
RUN echo "essdaq ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# create user
RUN useradd -p $1$GDleMP1C$Gk4BMmk/tu9AxXgi/dBcX. -ms /bin/bash essdaq

COPY run.sh /home/essdaq
RUN chmod 755 /home/essdaq/run.sh
RUN chown essdaq:essdaq /home/essdaq/run.sh

# avoid having to type (yes)
COPY known_hosts /home/essdaq/.ssh/
RUN chmod 644 /home/essdaq/.ssh/known_hosts
RUN chown -R essdaq:essdaq /home/essdaq/.ssh

RUN chown -R essdaq:essdaq /home/essdaq/

USER essdaq

WORKDIR /home/essdaq

RUN echo "Usage: run.sh [branch] [mode]"
RUN echo "  branch default is master"
RUN echo "  mode default is auto (other values implies manual)"
#CMD ["./run.sh"]
