{
 "title": "LoKI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Packet Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.loki.0.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(scale(perSecond(efu.loki.0.receive.dropped), 8), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.loki.0.receive.bytes, 8)), 'bits/s')"
    }
   ]
  },
  {
   "title": "Readout Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.loki.0.readouts.count), 'readouts/s')"
    }
   ]
  },
  {
   "title": "Readout Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "perSecond(efu.loki.0.readouts.error_header)"
    },
    {
     "target": "perSecond(efu.loki.0.readouts.error_seqno)"
    },
    {
     "target": "perSecond(efu.loki.0.readouts.error_size)"
    },
    {
     "target": "perSecond(efu.loki.0.readouts.error_buffer)"
    },
    {
     "target": "perSecond(efu.loki.0.readouts.error_bytes)"
    },
    {
     "target": "perSecond(efu.loki.0.readouts.error_type)"
    },
    {
     "target": "perSecond(efu.loki.0.readouts.error_version)"
    }
   ]
  },
  {
   "title": "Event rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.loki.0.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.loki.0.events.geometry_errors), 'geom errors/s')"
    },
    {
     "target": "alias(perSecond(efu.loki.0.events.udder), 'udder events/s')"
    }
   ]
  },
  {
   "title": "Idle/Uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.loki.0.thread.processing_idle), 'processing idle/s')"
    },
    {
     "target": "alias(efu.loki.0.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Output rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(scale(efu.loki.0.transmit.bytes, 8)), 'bis/s')"
    }
   ]
  }
 ]
}