{
 "title": "Multigrid Mesytec SNS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.mgmesytec.*" }
  ]
 },
 "panels": [
  {
   "title": "Packets/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.rx_packets)"
    }
   ]
  },
  {
   "title": "bytes/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mgmesytec.$region.rx_bytes, 0.001))"
    }
   ]
  },
  {
   "title": "Triggers/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.parser_triggers)"
    }
   ]
  },
  {
   "title": "Bad triggers/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region)"
    }
   ]
  },
  {
   "title": "Readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.readouts_total)"
    }
   ]
  },
  {
   "title": "Readouts discarded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(efu.mgmesytec.$region.rx_discarded_bytes, #B)",
     "targetFull": "asPercent(efu.mgmesytec.$region.rx_discarded_bytes, efu.mgmesytec.$region.readouts_total)"
    }
   ]
  },
  {
   "title": "Input Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.rx_packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mgmesytec.$region.rx_bytes, 8)), 'bits/s')"
    }
   ]
  },
  {
   "title": "Parsing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.rx_bytes), 'bytes received')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.rx_discarded_bytes), 'SIS discarded bytes')"
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.parser_triggers), 'total')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.bad_triggers), 'bad triggers')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.bus_glitches), 'bus glitches')"
    }
   ]
  },
  {
   "title": "Bus glitches",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.mgmesytec.$region.builder_glitch_rejects"
    }
   ]
  },
  {
   "title": "Timing errors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "efu.mgmesytec.timing_errors" }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.mgmesytec.$region.events_total"
    }
   ]
  },
  {
   "title": "Events/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.events_total)"
    }
   ]
  },
  {
   "title": "Tx Bytes/s",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mgmesytec.$region.tx_bytes, 0.000001))"
    }
   ]
  },
  {
   "title": "Tx Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(efu.mgmesytec.$region.tx_bytes, 1e-9)"
    }
   ]
  },
  {
   "title": "Uptime/idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(efu.mgmesytec.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_total), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_bad), 'bad events/s')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_time_err), 'timing err/s')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.readouts_total), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_total), 'events/s')"
    }
   ]
  },
  {
   "title": "Output Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_total), 'event/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.mgmesytec.$region.tx_bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.kafka.produce_fails), 'prod fail/s')"
    }
   ]
  }
 ]
}