{
 "title": "Multigrid Mesytec SNS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "region", "query": "efu.mgmesytec.*" }
  ]
 },
 "panels": [
  {
   "title": "Packets/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.rx_packets)"
    }
   ]
  },
  {
   "title": "bytes/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mgmesytec.$region.rx_bytes, 0.001))"
    }
   ]
  },
  {
   "title": "Triggers/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.parser_triggers)"
    }
   ]
  },
  {
   "title": "Bad triggers/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region)"
    }
   ]
  },
  {
   "title": "Readouts/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.readouts_total)"
    }
   ]
  },
  {
   "title": "Readouts discarded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(efu.mgmesytec.$region.rx_discarded_bytes, #B)",
     "targetFull": "asPercent(efu.mgmesytec.$region.rx_discarded_bytes, efu.mgmesytec.$region.readouts_total)"
    }
   ]
  },
  {
   "title": "Culled/event",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "divideSeries(efu.mgmesytec.readouts_culled, #B)",
     "targetFull": "divideSeries(efu.mgmesytec.readouts_culled, efu.mgmesytec.events)"
    }
   ]
  },
  {
   "title": "Packets received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.net.nic_rx), 'NIC total')"
    },
    {
     "target": "alias(perSecond(efu.net.udp_rx), 'UDP total')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.rx_packets), 'received by EFU')"
    }
   ]
  },
  {
   "title": "Parsing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.readouts_total), 'bytes received')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.rx_discarded_bytes), 'SIS discarded bytes')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region), 'VMMR discarded bytes')"
    }
   ]
  },
  {
   "title": "% data lost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(scale(divideSeries(perSecond(efu.net.udp_rxperr), #B), 100), 'UDP packets lost')",
     "targetFull": "alias(scale(divideSeries(perSecond(efu.net.udp_rxperr), perSecond(efu.net.nic_rx)), 100), 'UDP packets lost')"
    },
    {
     "refCount": 1,
     "target": "alias(scale(divideSeries(perSecond(efu.mgmesytec.sis_discarded_bytes), #D), 100), 'discarded in SIS parsing')",
     "targetFull": "alias(scale(divideSeries(perSecond(efu.mgmesytec.sis_discarded_bytes), perSecond(efu.mgmesytec.$region)), 100), 'discarded in SIS parsing')"
    },
    {
     "target": "alias(scale(divideSeries(perSecond(efu.mgmesytec.vmmr_discarded_bytes), #D), 100), 'discarded in VMMR parsing')",
     "targetFull": "alias(scale(divideSeries(perSecond(efu.mgmesytec.vmmr_discarded_bytes), perSecond(efu.mgmesytec.$region)), 100), 'discarded in VMMR parsing')"
    }
   ]
  },
  {
   "title": "Bus glitches",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.mgmesytec.$region.builder_glitch_rejects"
    }
   ]
  },
  {
   "title": "Timing errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "efu.mgmesytec.timing_errors" }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "efu.mgmesytec.$region.events_total"
    }
   ]
  },
  {
   "title": "Events/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(efu.mgmesytec.$region.events_total)"
    }
   ]
  },
  {
   "title": "Tx Bytes/s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(efu.mgmesytec.$region.tx_bytes, 0.000001))"
    }
   ]
  },
  {
   "title": "Tx Bytes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(efu.mgmesytec.$region.tx_bytes, 1e-9)"
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.parser_triggers), 'total')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.bad_triggers), 'bad triggers')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.bus_glitches), 'bus glitches')"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.readouts_total), 'readouts parsed')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.readouts_culled), 'readouts culled in EFU step')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region), 'readouts discarded')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_total), 'good events')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_geometry_err), 'geometry errors')"
    },
    {
     "target": "alias(perSecond(efu.mgmesytec.$region.events_time_err), 'timing errors')"
    }
   ]
  }
 ]
}